exports.seed = function(knex, Promise) {
  return knex("teas")
    .del()
    .then(() => {
      return knex("teas").insert([
        { name: "Darjeeling First Flash",
    season: "March April",
    aroma: 5,
    body: 4,
    sweet: 4,
    bitter: 3,
    color:1,
    kind: "Darjeeling",
    recommend: "1",
    milk: false
 },
 { name: "Darjeeling Second Flash",
    season: "May June",
    aroma: 5,
    body: 4,
    sweet: 3,
    bitter: 4,
    color:3,
    kind: "Darjeeling",
    recommend: "3",
    milk: false
 },
 { name: "Darjeeling Autumnal",
 season: "October November",
 aroma: 5,
 body: 2,
 sweet: 4,
 bitter: 2,
 color:3,
 kind: "Darjeeling",
 recommend: "4",
 milk: true
},
{ name: "Assam First Flash",
season: "March April",
aroma: 5,
body: 2,
sweet: 4,
bitter: 1,
color:3,
kind: "Assam",
recommend: "5",
milk: true
},
{ name: "Assam Second Flash",
season: "May June",
aroma: 5,
body: 5,
sweet: 4,
bitter: 1,
color:4,
kind: "Assam",
recommend: "5",
milk: true
},
{ name: "Assam Autumnal",
season: "October November",
aroma: 5,
body: 5,
sweet: 1,
bitter: 5,
color:5,
kind: "Assam",
recommend: "5",
milk: true
},
{ name: "Nilgiri",
season: "September December",
aroma: 4,
body: 1,
sweet: 4,
bitter: 1,
color:3,
kind: "Nilgiri",
recommend: "5",
milk: true
},
{ name: "Nilgiri",
season: "September December",
aroma: 4,
body: 1,
sweet: 4,
bitter: 1,
color:3,
kind: "Nilgiri",
recommend: "5",
milk: false
},
{ name: "Nuwara Eliya",
season: "February March",
aroma: 4,
body: 2,
sweet: 2,
bitter: 4,
color:2,
kind: "Ceylon",
recommend: "5",
milk: false
},
{ name: "Dimbra",
season: "January February",
aroma: 4,
body: 2,
sweet: 2,
bitter: 4,
color:2,
kind: "Ceylon",
recommend: "5",
milk: false
},
]);
});
};
